- name: Run the equivalent of "apt-get update" 
  ansible.builtin.apt:
    update_cache: yes

- name: Copy passwords diccionary
  ansible.builtin.copy:
      src: ../files/diccionarios
      dest: /home/user/Documents/
      
- name: Copy brute force script
  ansible.builtin.copy:
      src: ../files/bruteForce.sh
      dest: /home/user/Documents/bruteForce.sh

- name: Remove apache2
  ansible.builtin.apt:
      name: apache2
      state: absent

