- name: Run the equivalent of "apt-get update" 
  ansible.builtin.apt:
    update_cache: yes
      
- name: Install python3
  ansible.builtin.apt:
    name: python3
    state: present
    
- name: Install python3-venv
  ansible.builtin.apt:
    name: python3-venv
    state: present
    
- name: Install python3-pip
  ansible.builtin.apt:
    name: python3-pip
    state: present
    
- name: Copy geckodriver 31.0
  ansible.builtin.copy:
      src: ../files/geckodriver_31.0
      dest: /usr/local/bin/geckodriver
      mode: '0755'
    
- name: Install selenium for python 3
  ansible.builtin.pip:
    name: selenium
    executable: pip3
      
- name: Copy victim bot python script
  ansible.builtin.copy:
      src: ../files/victimBot.py
      dest: /home/ubuntu/victimBot.py
      mode: '0755'
      
- name: Copy victim bot service
  ansible.builtin.copy:
      src: ../files/victimBot.service
      dest: /etc/systemd/system/victimBot.service
      mode: '0644'

- name: Start service victim bot
  ansible.builtin.service:
    name: victimBot
    state: started

- name: Pause for 20 seconds to wait cookie in stdout
  ansible.builtin.pause:
    seconds: 20

- name: Show PHP session cookie 
  ansible.builtin.shell: 
    cmd: journalctl | grep 'PHPSESSID'
